[alias]
xtask = "run --package xtask --"

# [target.x86_64-unknown-linux-gnu]
# rustflags = "--crate-type=cdylib"
#
# [target.x86_64-pc-windows-msvc]
# rustflags = "--crate-type=cdylib"
#
# [target.wasm32-unknown-unknown]
# rustflags = [
#   "--crate-type=staticlib",
#   "-Ctarget-cpu=mvp",
#   "-Zbuild-std=panic_abort,std",
# ]
